CREATE TABLE BONUSKAART(
	BONUSKAARTNUMMER INT NOT NULL
	NAAM VARCHAR(225)
	ADRES VARCHAR(225)
	WOONPLAATS VARCHAR(225)
)


CREATE TABLE TRANSACTIE(
	TRANSACTIENUMMER INT NOT NULL
	DATUM DATE
	TIJD TIME
	BONUSKAARTNUMMER INT PUBLIC
	FILIAAL NUMMER INT PUBLIC
)
	

CREATE TABLE AANKOOP(
	TRANSACTIENUMMER INT FOREIGN KEY
	PRODUCT INT FOREIGN KEY
	AANTAL INT
)
	

CREATE TABLE PRODUCT
	PRODUCTNUMMER INT NOT NULL
	OMSCHRIJVING VARCHAR(225)
	PRIJS DECIMAL(6,2)

CREATE TABLE FILIAAL
	FILIAALNUMMER INT NOT NULL
