DROP TABLE IF EXISTS BONUSKAART;
DROP TABLE IF EXISTS TRANSACTIE;
DROP TABLE IF EXISTS AANKOOP;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS FILIAAL;


CREATE TABLE BONUSKAART(
	BONUSKAARTNUMMER INT NOT NULL,
	NAAM VARCHAR(225),
	ADRES VARCHAR(225),
	WOONPLAATS VARCHAR(225));


CREATE TABLE TRANSACTIE(
	TRANSACTIENUMMER INT NOT NULL,
	DATUM DATE NOT NULL,
	TIJD TIME NOT NULL,
	BONUSKAARTNUMMER INT NOT NULL,
	FILIAALNUMMER INT NOT NULL
);
	

CREATE TABLE AANKOOP(
	TRANSACTIENUMMER INT NOT NULL,
	PRODUCT INT NOT NULL,
	AANTAL INT NOT NULL
);
	

CREATE TABLE PRODUCT(
	PRODUCTNUMMER INT NOT NULL,
	OMSCHRIJVING VARCHAR(225),
	PRIJS DECIMAL(6,2)
);


CREATE TABLE FILIAAL(
	FILIAALNUMMER INT NOT NULL
);


ALTER TABLE BONUSKAART ADD PRIMARY KEY(BONUSKAARTNUMMER);
ALTER TABLE TRANSACTIE ADD PRIMARY KEY(TRANSACTIENUMMER, BONUSKAARTNUMMER, FILIAALNUMMER);
ALTER TABLE AANKOOP ADD PRIMARY KEY(TRANSACTIENUMMER);
ALTER TABLE PRODUCT ADD PRIMARY KEY(PRODUCTNUMMER);
ALTER TABLE FILIAAL ADD PRIMARY KEY(FILIAALNUMMER);

ALTER TABLE TRANSACTIE
ADD CONSTRAINT TRANSACTIE_BONUSKAARTNUMMER
FOREIGN KEY (BONUSKAARTNUMMER) REFERENCES BONUSKAART(BONUSKAARTNUMMER);

ALTER TABLE TRANSACTIE
ADD CONSTRAINT TRANSACTIE_FILIAALNUMMER
FOREIGN KEY (FILIAALNUMMER) REFERENCES FILIAAL(FILIAALNUMMER);

ALTER TABLE AANKOOP
ADD CONSTRAINT AANKOOP_TRANSACTIENUMMER
FOREIGN KEY (TRANSACTIENUMMER) REFERENCES TRANSACTIE(TRANSACTIENUMMER)

INSERT INTO BONUSKAART VALUES (65472335)
INSERT INTO BONUSKAART VALUES (12345678, Annette, Vredenburg 12, Utrecht)
INSERT INTO BONUSKAART VALUES (98765, Jazim, Trekkerspad 5, Houten)
INSERT INTO FILIAAL VALUES (98765, Jazim, Trekkerspad 5, Houten)


